import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import useSWR from 'swr'

const fetcher = (url: string) => fetch(url).then((res) => res.json());

export default function Home() {


  const { data, error } = useSWR('/api/aftonbladet', fetcher)

  if (error) return <div>failed to load</div>
  if (!data) return <div>loading...</div>

  console.log(data)

  return (
    <div className={styles.container}>
      <Head>
        <title>Roliga Nyheter</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          SENASTE NYTT
        </h1>

        <div className={styles.grid}>

            {
              data.map( (item: any) => {
                return (
                  <div key={item.title} style={{

                  }}>
                    <h1>{item.title}</h1>
                    <Image width={300} height={300} src={item.image} alt={item.title} style={{
                      float: 'left',
                      marginRight: '1rem'
                    }} />
                    <p><i>{item.newSummary}</i></p>
                  </div>
                )
              })
            }


        </div>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  )
}
